project:
  type: website
  output-dir: docs

website:
  title: "HasturBoxerShorts"

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
        
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/zoe-l-wilson/
      - icon: github
        href: https://github.com/Zoe-Lorraine-Wilson

  sidebar:
    - title: "Contents"
      style: "docked"
      background: light
      contents: auto
      


format:
  html:
    theme: minty
    css: styles.css

editor: visual

