project:
  type: website
  output-dir: docs

website:
  title: "HasturBoxerShorts"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "About this blog"
        href: about.qmd
    navbar:
    left: 
      - text: "Home"
        href: index.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/zoe-l-wilson/
      - icon: github
        href: https://github.com/Zoe-Lorraine-Wilson
format:
  html:
    theme: minty
    css: styles.css

editor: visual

